spring.profiles.active: development
spring.application.name: sample-source-app
server.port: 8080

# name of the location where the messaging is going to be delivered at the middleware level.
## for kafka it means the topic name
## for rabbit it means the exchange name
## for kinesis it means the stream name
spring.cloud.stream.bindings.output.destination: hello

# kinesis specific configuration
## waits until message is delivered to kinesis
spring.cloud.stream.kinesis.bindings.output.producer.sync: true

# default binder implementation. Supported values: kinesis, rabbit
spring.cloud.stream.defaultBinder: kinesis

---

# used when spring.cloud.stream.defaultBinder: kinesis
cloud.aws.region.static: eu-west-1

# used when spring.cloud.stream.defaultBinder: rabbit
spring.rabbitmq.addresses: localhost:5672

# not required for higher environments. In case message is published to rabbitmq exchange this configuration will ensure rabbitmq forwards the message to queues below
# this should not necessarily be enforced by the producer application but for local testing is fine
spring.cloud.stream.bindings.output.producer.requiredGroups: transformer-app

# it should be turned on whe using localstack kinesis https://github.com/localstack/localstack
kinesis.local.enabled: true