# common settings for all environments
spring.profiles.active: development
spring.application.name: sample-sink-app
server.port: 8081
spring.cloud.stream.bindings.input.group: sink
spring.cloud.stream.bindings.input.destination: hello

# default binder implementation. Supported values: kinesis, rabbit
spring.cloud.stream.defaultBinder: kinesis
---

# everything below is active only during development
spring.profiles: development
# used when spring.cloud.stream.defaultBinder=kinesis
cloud.aws.region.static: eu-west-1
# used when spring.cloud.stream.defaultBinder=rabbit
spring.rabbitmq.addresses: localhost:5672

spring.cloud.stream.bindings.input.consumer.concurrency: 1
spring.cloud.stream.bindings.input.consumer.maxAttempts: 2
spring.cloud.stream.bindings.input.consumer.instanceCount: 1
spring.cloud.stream.bindings.input.consumer.instanceIndex: 1
# it should be turned on whe using localstack kinesis https://github.com/localstack/localstack
kinesis.local.enabled: true
management.endpoints.web.exposure.include: "*"